### ISSUE TITLE
Document communication flow between nmrium-react-wrapper (iframe) and the parent application

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#11]
@noura @hamed-musallam Please document the tentative plan/communication possibilities and final choice (I believe window-based observable), including the reason to choose that solution so we could discuss potential pitfalls.

**Comment by hamed-musallam** [comment]
@CS76 
we have two options (custom events, window observable) that will serve our purpose but we have to keep in mind this:

1. custom events

   - Independent of any framework
   - Customizable
   - other components don’t need to know their parents
   - on the other hand,
             -  we have to follow certain naming conventions to prevent conjunction with others, maybe add prefix 
              nmr-wrapper:<event name>
             - compatibility 
             
![image](https://user-images.githubusercontent.com/35760236/163366254-ba5e1bfc-a4b2-4b70-9387-95613bd86f7b.png)

          

2. window observable 
    - it has the advantages of the custom events
    - on the other hand, it uses a Window object and that means namespace events/subscribers are not completely isolated so we have to use a unique name to prevent the conflict with others that might use the window object for their needs

**Comment by hamed-musallam** [comment]
@CS76 
if we need only to trigger and capture an event and nothing more we can use a custom event unless if you see that there are browser compatibility issues then we can go with a window-based observable

**Comment by NishaSharma14** [comment]
This has to go to the nmrxiv documentation site. Create an issue there.
