### ISSUE TITLE
Display information about the version of nmrium-react-wrapper

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrium-react-wrapper#111]
Right now from the endpoint https://nmrium.nmrxiv.org/ it's unclear which version of nmrium-react-wrapper we are using.

**Comment by hamed-musallam** [comment]
based on the last discussion with Chandu we agreed to the endpoint should point to the latest version as what we have in the wrapper (development) branch.

**Comment by NishaSharma14** [comment]
yes, but this should be a nice to-have feature. Maybe if we can provide an About section which will show the complete CHANGE.log

**Comment by harivyasi** [comment]
Hi, just a small input (since I brought up this issue with @NishaSharma14): I think having access to version (commit) number is essential for reproducibility.

**Comment by CS76** [comment]
Add a info icon on the bottom left corner (fixed, top) so it appears to be part of nmrium but its just an overlay. When clicked should display info about the nmrium react wrapper version and commit hash.

<img width="713" alt="Screenshot 2023-08-28 at 11 30 47" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/b916a3aa-5b9d-4e68-b452-5ee0cfba740f">

Complete view

![Screenshot 2023-08-28 at 11 27 25](https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/6bbb7a3e-2019-434b-8906-a0d7d39f44f9)

Pop up modal example

![Group 3](https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/184d160b-6cd7-47bc-be74-bccdf423692c)

**Comment by hamed-musallam** [comment]
@CS76  @NishaSharma14 

I modified the development deployment workflow to automatically update the src > versionInfo.ts file with the reference to the latest commit https://github.com/NFDI4Chem/nmrium-react-wrapper/commit/732f5db00d634a82962f9c1fa2e99307dc254e93. could apply a similar thing when deploying to the production environment, Update versionInfo.ts file with version number.

**Comment by hamed-musallam** [comment]
@CS76 @CS76 

take care that we have a branch in our repository for each production version and by that we can point to it in the about section `https://github.com/NFDI4Chem/nmrium-react-wrapper/tree/<version number>` 

https://github.com/NFDI4Chem/nmrium-react-wrapper/blob/8dd0eb9e918449b5100cb2c8e6f913ec2bb10366/src/modal/AboutUsModal.tsx#L83-L110

**Comment by CS76** [comment]
Commit is good to go @hamed-musallam (if its deployed we know the branch details so that would be redundant)

**Comment by hamed-musallam** [comment]
@CS76 

in this case, the development version reference will be the same as the production version which is supposed to not.

**Comment by NishaSharma14** [comment]
@hamed-musallam thanks for the implementation.
but instead of nmrium we have to provide link for nmrium-react-wrapper GitHub

<img width="767" alt="image" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/54287612/78820ba4-6869-4f1a-8074-0a3e9cec4d0f">
