### ISSUE TITLE
Visualise 2D NMR spectral for compatible file formats and save preview by persisting the generated spectra

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#12]
@nrayya @hamed-musallam please break this down to sub-tasks and assign b/w you both pls

**Comment by hamed-musallam** [comment]
@CS76 

the first part of the ticket NMRium supported it by default, the second part we need to discuss about it and see what do you mean in 

> save preview by persisting the generated spectra

**Comment by CS76** [comment]
Saving previews of the spectra
- [ ] Implement toolbar on the nmrium-wrapper using external package
- [ ] Parent application raises event - savePreview
- [ ] NMRium wrapper then listens to the event, export spectra as SVG and communicates back to the parent application via the event channel.

**Comment by hamed-musallam** [comment]
https://github.com/cheminfo/nmrium/issues/1569

**Comment by NishaSharma14** [comment]
To be tested on the new version.

**Comment by NRayya** [comment]
Current status: Bruker

- 2D FID: a message shown to the user:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/82588017/184627832-ff800625-8b57-4880-8a45-c16cd47d269a.png">

-  Processed 2D: No message shown 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/82588017/184627881-b661c9d4-9742-47fc-8abf-3683019e2e9d.png">

**Comment by NRayya** [comment]
Current status: jcamp:

- 2D FID: a message shown to the user:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/82588017/184630686-2811382b-56c5-4587-9c74-f71d13742df4.png">

- Processed 2D: viewed 
- 
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/82588017/184630838-aecbdcbc-4a49-48d4-899c-deaf1a067176.png">

**Comment by NRayya** [comment]
Current status:
FID is showing the error message for dx, jdf, and Bruker.
FT is working for dx and Bruker
