### ISSUE TITLE
Loading icon rendering

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#124]
Instead of showing the "Drag and drop here a JCAMP-DX, Bruker folder, JOEL jdf or nmrium file" loading icon should appear by default when the nmr-wrapper:load event is triggered. On low bandwidth networks, it takes forever to load the spectra (the loading icon is shown after quite some time)  this is misleading the user indicating something is wrong with the spectra
 
https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/6a5b8d5f-d36a-4c7e-a755-2966ed1ce50a

**Comment by hamed-musallam** [comment]
@CS76 

This is something NMRium has nothing to do about it, it seems that there is time between loading the wrapper and triggering loading the spectra, which I think is from the side of nmrXiv

**Comment by CS76** [comment]
Resolving this now with the default message update
