### ISSUE TITLE
Ability to overwrite default text in the viewer

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#125]
Repositories like nmrxiv and Chemotion should be able to overwrite the "Drag and drop here a JCAMP-DX, Bruker folder, JOEL jdf or nmrium file." default text with more relevant information (as per resource requirements). The current default message is misleading the users, especially when the viewing spectra in a read only views

**Comment by hamed-musallam** [comment]
@CS76 

We have the ability to customize the default message, Which name do you think is better to represent our need: `defaultMessage`, `defaultEmptyMessage`, or simply `message`?

https://nmriumdev.nmrxiv.org/?defaultEmptyMessage="nmrXiv message"
