### ISSUE TITLE
Peak picking and persisting the peaks to the back end

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#13]
@nrayya @hamed-musallam

**Comment by hamed-musallam** [comment]
@CS76 @NRayya

we need to put in our mind when we work with the data that we get from onDataChange call-back function, we return the whole new state of NMRium, which contain all the data and not only the peaks of the new record, for example, under the peaks object you will find all the peaks and not only the new peaks that you add.

**Comment by hamed-musallam** [comment]
@CS76 @NRayya 

we should split it into smaller tasks and clarify your needs
