### ISSUE TITLE
Differences in nmrium exported data as sources and wrapper event data

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#133]
Imported [Pseudopelletierin_CDCl3.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/12439976/Pseudopelletierin_CDCl3.zip) spectra on nmrxiv and processed the spectra. 

Saved the nmrium-react-wrapper data export as .nmrium file and also manually exported as nmrium json using export data as option.

Later loaded both the files by drag and drop produce different results. Also data (json) sizes are a lot different.

1) Spectra loaded on nmrium (drag and drop) from wrapper data export

<img width="2298" alt="Screenshot 2023-08-25 at 15 41 39" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/13e1e57d-d296-44bc-98f7-5f660343eed9">
<img width="1152" alt="Screenshot 2023-08-25 at 15 41 30" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/84df0dec-1f04-4730-a61c-c08696470776">

2) Spectra loaded on nmrium (drag and drop) from nmrium export data as (sources) option

<img width="2304" alt="Screenshot 2023-08-25 at 15 42 16" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/031ae50a-5b9e-4f4a-a924-13c87a5ca057">
<img width="2302" alt="Screenshot 2023-08-25 at 15 42 08" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/742a0fb6-a29d-40a0-ba4a-266e138f2e34">

Wrapper data is almost 4.7 MB while nmrium export with sources is just 6KB

Files for tesing

[wrapper_data_Pseudopelletierin_CDCl3.nmrium.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/12439941/wrapper_data_Pseudopelletierin_CDCl3.nmrium.zip)
[Pseudopelletierin_CDCl3_0.nmrium.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/12439944/Pseudopelletierin_CDCl3_0.nmrium.zip)

**Comment by hamed-musallam** [comment]
The callback function returns the entire 'nmrium' object, so we need to apply mapping and filtering operations to it, 
The size issue comes from the `data` and `originalData` objects which a big 1D or 2D array objects, No need for them if we have a reference to the original files
