### ISSUE TITLE
Peak picking tool needs to be enabled by default in the embeded workspace

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#136]
<img width="861" alt="Screenshot 2023-08-28 at 13 54 30" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/33ef12b2-d592-4aa7-8272-7dc4fc472696">

**Comment by hamed-musallam** [comment]
@CS76 

Please check https://github.com/cheminfo/nmrium/issues/1839

**Comment by hamed-musallam** [comment]
Closed by #158
