### ISSUE TITLE
Auto delete branch when PR is merged.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrium-react-wrapper#141]

**Comment by hamed-musallam** [comment]
@NishaSharma14 

Did you make any additional modifications to the project settings on GitHub, or did you just activate the auto-delete feature?

**Comment by NishaSharma14** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

but before this we have to make sure we have branch protection rule activated for development and main which is already there.
