### ISSUE TITLE
The nmrium file can't be read

### ISSUE THREAD

**Issue by phuang26** [NFDI4Chem/nmrium-react-wrapper#164]
Hi, 

Encountering a problem uploading the NMRium file. Please see the following information

**Error in the Console**

```
cloneData2D.js:21 Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at addCloneData (cloneData2D.js:21:31)
    at cloneData2D (cloneData2D.js:10:13)
    at resetDataToOrigin (FiltersManager.js:13:15)
    at enableFilter (FiltersManager.js:102:5)
    at reapplyFilters (FiltersManager.js:92:5)
    at initiateDatum2D (initiateDatum2D.js:35:5)
    at initSpectra (LoadActions.js:88:26)
    at setData (LoadActions.js:64:36)
    at initData (LoadActions.js:114:9)
    at handleLoadDropFiles (LoadActions.js:148:16)
    at innerSpectrumReducer (Reducer.js:135:24)
```

**Video**

[nmrium-read-issue.webm](https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/70375322/a4b52d93-af99-448d-9530-f9ad641b4f2d)

**File** please try 42_error.nmrium

- https://drive.google.com/drive/folders/1EK9AgshG4c_1LK1e3y5QM64Bc6j-hV9k?usp=sharing

**Comment by hamed-musallam** [comment]
Hello 

It would be preferable if you could zip the file and upload it here, ensuring continued accessibility. Currently, we are unable to access your file due to a lack of permissions

**Comment by hamed-musallam** [comment]
After reviewing your files, I identified the issue in how you save the NMRium object in the backend.

The NMRium file or object that you save in the backend should include the 'version' object, which is mandatory for proper migration.

Both NMRium files, based on their structure, are version 4 of the data structure. Consequently, the NMRium file needs to be reshaped, and I believe this might have been an oversight on your part, as you seem to have extracted only what's inside the 'data' object.

Based on that the 42_error.nmrium file should look like this 
![Screenshot 2023-11-10 at 11 45 00](https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/35760236/a643118f-121b-4e3f-b296-ea5b8a2fe00f)

**Comment by phuang26** [comment]
Hi @hamed-musallam, 

Thank you for your prompt response. As these two files are from different ChemSpectra versions, it seems there might be some issues on our side. I will check with Lan. Thanks a lot.
