### ISSUE TITLE
Embedded mode update

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#170]
Panels:
- Spectra
- Information
- Peaks
- Processings
- Integrals
- Ranges
- Assignments
- Chemical structures
- Summary

Side panel (default):
-  Should be open: True
-  Width: 180px

Float structure:
- If a molecule is present, float it by default

**Comment by hamed-musallam** [comment]
we can not float the molecule by default from the workspace, it is a different story that we control from the `view object`, I will see how I can do it.

**Comment by CS76** [comment]
This is now moved to nmrxiv workspace

**Comment by CS76** [comment]
Additional configuration

1) Disable Peaks/Integral tools
2) Disable Peaks/Integral panels

**Comment by CS76** [comment]
<img width="320" alt="Screenshot 2024-01-13 at 18 01 47" src="https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/4065285/b096ef2a-f7cd-4f9c-9148-3c9ec0ebdd63">

Hide all options except full screen
