### ISSUE TITLE
2D NMR display / processing issues

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#186]
Compare

https://nmrium.nmrxiv.org/?defaultEmptyMessage=loading&workspace=embedded
https://nmrium.nmrxiv.org/?defaultEmptyMessage=loading&workspace=nmrxiv

[42 - only blank.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/14019693/42.-.only.blank.zip)

[HSQC-HSQC.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/14019694/HSQC-HSQC.zip)

**Comment by hamed-musallam** [comment]
@CS76 

the nmrXiv workspace is still not in production, the changes we made are in the development environment.

**Comment by CS76** [comment]
@hamed-musallam I believe we now have the workspace on production. Lets close the issue if its no longer relevant

**Comment by hamed-musallam** [comment]
It is resolved. We now have the nmrXiv workspace on the production.
