### ISSUE TITLE
Load Bruker Zip files via URL

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#20]
Schema to load Bruker Zip files from URL ?? @hamed-musallam

**Comment by hamed-musallam** [comment]
Let me first discuss it with the team to see if it has to be done directly from nmrium like jcamURL or do it in the nmrium wrapper. And also the other files format maybe we should take care about it.

**Comment by CS76** [comment]
FYI - file formats that we (nmrXiv) would like to look into - https://docs.nmrxiv.org/docs/introduction/file-format

**Comment by hamed-musallam** [comment]
@CS76 

it is done, you can check it at the development branch 

```ts
  observableEvents.trigger('loadURLs', {
              urls: [
                'https://cheminfo.github.io/nmr-dataset-demo/cytisine/13c.jdx',
                'https://cheminfo.github.io/nmr-dataset-demo/cytisine/1h.jdx',
                'https://cheminfo.github.io/bruker-data-test/data/zipped/aspirin-1h.zip',
              ],
            });
```

**Comment by hamed-musallam** [comment]
@CS76 

I created an event  "error" triggering when loadURls failed to load the spectra before pushing it to NMRium

```ts
observableEvents.on('error',(e:error)=>{
 //put your code here
})
```
