### ISSUE TITLE
Remove test buttons on the top of the NMRium component

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#23]
Two possible solutions we can adapt

1) Display the buttons only on the development instance. The production version should have this automatically hidden (subdomain check or via build process). Make sure this doesn't add up to the loading time of the application.

2) Totally hide this and register keyboard shortcuts to trigger these events. For example 

Shft+Ctrl+1 => Test load custom event
Shft+ctrl+2 => Test load observable
Shft+ctrl+2 => Test load via URLS

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/4065285/168749385-7d8e3c6f-3fb5-4985-8c3d-13b2ec2656e2.png">

**Comment by hamed-musallam** [comment]
@CS76 
 I will use playwright for testing and remove the buttons completely

**Comment by hamed-musallam** [comment]
closed by https://github.com/NFDI4Chem/nmrium-react-wrapper/commit/4e0848f93e26955507ff1c57da6dd0aa1a5cc947
