### ISSUE TITLE
Propogate onChange event from the nmrium component to the parent

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#28]
We would like to capture all the changes that our users might perform on the spectra. So, to enable this we need to propagate the onChange event from the nmrium react component to the parent via window message event and the parent application will then process/persist the data to the back end.

**Comment by hamed-musallam** [comment]
closed by 9639440c92d5b7129124e432d68593815ddb3a98 , 439fe7179943b28691f2c01f9960a74e1b3f9039 , 4b13659c03c3fdcf27a3ccaf18982b7ac30f87d6
