### ISSUE TITLE
Enable read only mode 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#29]
Once the data is published to the public, nmrXiv users would like to look into the assignments (browser) and other related assay parameters. 

We need to offer a read-only view of the spectra using nmrium without the options or with the options disabled. The spectra viewer still needs to be interactive while the side panels just need to display data.

**Comment by hamed-musallam** [comment]
@CS76 

What do you mean 
 >viewer still needs to be interactive

do you mean the user can only zoom in/out and the other tools are not visible or deactivated?

I think it is better to let the user interact and change the data inside the NMRium but the changes he did will not save in the backend, this can be done at the parent application or at the level of the wrapper by not triggering the `dataChange` event?

**Comment by CS76** [comment]
By saying interactive I meant the user to be able to zoom in/out of the spectra, open different side panels and see the data there (peaks picked, ranges, correlation charts, peak assignments etc.). 

If we allow the user to be able to click and re-pick peaks in the NMRium it might confuse them. They can fork the spectral data and re-analyse/play with the spectra but not on the public-facing pages.

**Comment by CS76** [comment]
NMRium currently cannot offer read-only mode due to architectural constraints. This needs to be / can be handled at the parent application level by blocking the reading process.

NMRium is deployed as a viewer/editor (components) on nmrXiv. The viewer component offers read-only mode. #todo - warn users when new spectrum is dragged and dropped.
