### ISSUE TITLE
Handle transmit analysed data

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#30]
### What we need:
- Transmit analysed data to other parties

### Current status:
- Analysed data is saved as a downloaded file [see the video]
https://user-images.githubusercontent.com/9006482/174767853-86d5a395-1bb8-4060-b8ba-dda522f2a7c1.mp4

**Comment by NishaSharma14** [comment]
@baolanlequang This must be fixed now. Can you please test this once?
