### ISSUE TITLE
Retrieve file name when saving preview image

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#33]
## How the workflow should be?
Let's say the user sends 2 files named `analyse_1.dx` and `analyse_2.zip` to the wrapper. 
The user wants to save the preview image depending on which file she/he is working on. 
She/he want to save the file name of the preview image as same as the file that she/he sent. For example, if she/he is working on `analyse_2.zip`, the preview image should be `analyse_2.svg` or '`analyse_2.png`.

## Questions
1. Do we have any option for this workflow?
2. If not, is it possible to implement it?

**Comment by NishaSharma14** [comment]
Related to https://github.com/NFDI4Chem/nmrxiv-nodejs-microservice/issues/2

**Comment by CS76** [comment]
Reopen this in nmrkit. Closing this here.
