### ISSUE TITLE
Missing peaks picking option

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#37]
It should enable the peaks picking option that allows users can select peaks manually. The current version doesn't have it. See the screenshot:

![Missing peaks picking option](https://user-images.githubusercontent.com/9006482/185122835-3f998102-2dd0-4b6b-869c-1e5944ce8472.png)

**Comment by baolanlequang** [comment]
@CS76 An spectra example
[220204-5-H202.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/9459575/220204-5-H202.zip)

**Comment by CS76** [comment]
Closing this in favour of release nmrium-v.0.31.0
