### ISSUE TITLE
NMRium cannot view 2D spectra as zip file

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#40]
In NMRium test page, we can view the 2D data, but in NMRium wrapper we can't. See the video below:

https://user-images.githubusercontent.com/9006482/185863826-e143ccda-ee54-42ff-8e9a-06124866f2e3.mp4

Here is the file that was used in the video:
[12.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/9392197/12.zip)

**Comment by NishaSharma14** [comment]
Duplicate #300
Tracked in PR https://github.com/cheminfo/nmrium/issues/1627

**Comment by baolanlequang** [comment]
It was fixed.
