### ISSUE TITLE
save version object with the other data inside the database

### ISSUE THREAD

**Issue by hamed-musallam** [NFDI4Chem/nmrium-react-wrapper#47]
@CS76 

```ts
{
version: <number>
spectra:[],
molecules:[],
// ... other properties 
}
```

what is missing in the data you save in the database is the version object which is important for the migration process that is done when importing the .nmrium object inside the NMRium and without it the NMRium went be able to display the data.

another thing worth mentioning is the migration functionality moved to nmr-load-save package which means we can use the migration separately if we need it to migrate the old data

**Comment by CS76** [comment]
Done. Part of the commit #[a183e6c](https://github.com/NFDI4Chem/nmrxiv/commit/a183e6c832c4bd28544b6090d60b2c4754d99984)
