### ISSUE TITLE
 NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrium-react-wrapper#49]
![image](https://user-images.githubusercontent.com/82588017/198563542-0178ba53-b1ca-4446-82b8-3b2a73093d64.png)

Here are the files, we are facing the issue with datasets 2,6, and 7
https://cloud.uni-jena.de/s/588LfmRnyTbiDT3

**Comment by CS76** [comment]
Could you please check the network tab in the console and provide more details if there is a server error?  A possible reason might be that the original file is missing or 500 error on the server side while streaming the file

**Comment by NRayya** [comment]
The error is solved
