### ISSUE TITLE
Spectra loaded via URL is being downloaded several times

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#95]
<img width="1436" alt="Screenshot 2023-04-20 at 18 42 49" src="https://user-images.githubusercontent.com/4065285/233432946-ef09ea70-dbe7-4d98-8bf0-e1fb862432dd.png">

Test it on nmrxiv dev site for more details please.

**Comment by CS76** [comment]
https://nmriumdev.nmrxiv.org/#/demo

**Comment by hamed-musallam** [comment]
@CS76 

currently, we have this behavior:

1- the first time, Which is a necessary step, currently NMRium we can not accept URLs directly so we need to read the files to generate the {Source, and sourceSelector}  
https://github.com/NFDI4Chem/nmrium-react-wrapper/blob/84bb1e884e64b0741f39afc8fc4daefa2c08597e/src/hooks/useLoadSpectra.ts#L35

2- the second time when we pass the JSON object to NMRium and start to read the files and display the Spectra
