### ISSUE TITLE
Avoid adding .zip extension to the download url

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrium-react-wrapper#96]
https://github.com/NFDI4Chem/nmrium-react-wrapper/blob/84bb1e884e64b0741f39afc8fc4daefa2c08597e/src/hooks/useLoadSpectra.ts#L30

looks like .zip is being appended to the download link URL and this is going to break download links

**Comment by hamed-musallam** [comment]
Without having an extension the NMRium will not be able to identify the file and handle it in the proper way based on it is extension
